apiVersion: v1
kind: Service
metadata:
  name: ftps-serv
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - protocol: TCP
      name: http
      port: 21
      targetPort: 21
    - protocol: TCP
      name: http2
      port: 21000
      targetPort: 21000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-depl
  labels:
    app: ftps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 21000
