apiVersion: v1
kind: Service
metadata:
  name: influxdb-serv
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-depl
  labels:
    app: influxdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb_image
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        volumeMounts:
          - mountPath: "/root/.influxdb"
            name: influxdb-vol
      volumes:
      - name: influxdb-vol
        persistentVolumeClaim:
          claimName: influxdb-vol-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-vol
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: "/mnt/data_influx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-vol-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
